### ISSUE TITLE
Error building compiler due with error code 9009 from fssrgen.targets

### ISSUE THREAD

**Issue by peter-campora** [Microsoft/visualfsharp#1775]
Please provide a succinct description of the issue.
The compiler doesn't build under the default build.cmd
#### Repro steps

Provide the steps required to reproduce the problem

1. Step A
run build.cmd after cloning repo

#### Expected behavior

A successful build of the visualfsharp compiler

#### Actual behavior

Get two error messages below:

"C:\Users\John Peter\Documents\visualfsharp\src\fsharp-proto-build.proj" (default target) (1) ->
"C:\Users\John Peter\Documents\visualfsharp\src\fsharp\FSharp.Build-proto\FSharp.Build-proto.fsproj" (Build target) (2)
 ->
(CallFsSrGen target) ->
  C:\Users\John Peter\Documents\visualfsharp\src\scripts\fssrgen.targets(27,5): error MSB3073: The command "C:\Users\John Peter\Documents\visualfsharp\src\fsharp\FSharp.Build-proto\..\..\..\packages\FSharp.Compiler.Tools.4.0.1.19\tools\fsi.exe --exec C:\Users\John Peter\Documents\visualfsharp\src\scripts\fssrgen.fsx "C:\Users\John Peter\Documents\visualfs
harp\src\fsharp\FSharp.Build\FSBuild.txt" "obj\Proto\net40\FSBuild.fs"  "obj\Proto\net40\FSBuild.resx" " exited with code 9009. [C:\Users\John Peter\Documents\visualfsharp\src\fsharp\FSharp.Build-proto\FSharp.Build-proto.fsproj]

"C:\Users\John Peter\Documents\visualfsharp\src\fsharp-proto-build.proj" (default target) (1) ->
"C:\Users\John Peter\Documents\visualfsharp\src\fsharp\FSharp.Compiler-proto\FSharp.Compiler-proto.fsproj" (Build targe
t) (3) ->
  C:\Users\John Peter\Documents\visualfsharp\src\scripts\fssrgen.targets(27,5): error MSB3073: The command "C:\Users\John Peter\Documents\visualfsharp\src\fsharp\FSharp.Compiler-proto\..\..\..\packages\FSharp.Compiler.Tools.4.0.1.19\tools
\fsi.exe --exec C:\Users\John Peter\Documents\visualfsharp\src\scripts\fssrgen.fsx "C:\Users\John Peter\Documents\visualfsharp\src\fsharp\FSComp.txt" "obj\Proto\net40\FSComp.fs" "obj\Proto\net40\FSComp.resx" " exited with code 9009. [C:\Users\John Peter\Documents\visualfsharp\src\fsharp\FSharp.Compiler-proto\FSharp.Compiler-proto.fsproj]

#### Related information 

Provide any related information 

* Operating system - Windows 10
* Branch
* .NET Runtime, CoreCLR or Mono Version- .NET 4.6.2
* Editing Tools (e.g. Visual Studio Version) Visual Studio Enterprise 2015

**Comment by KevinRansom** [comment]
@peter-campora 
Which version of VS was installed, VSSDK and Windows SDK?

Thanks

KEvin

**Comment by dsyme** [comment]
It's possible it's a space in the path name ``John Peter``

**Comment by dsyme** [comment]
@peter-campora Should be fixed by https://github.com/Microsoft/visualfsharp/pull/1793

**Comment by peter-campora** [comment]
@dsyme I still get the errors below when building in the path with spaces in it, but it built fine in another location.


"C:\Users\John Peter\Documents\visualfsharp\src\fsharp-proto-build.proj" (default target) (1) ->
"C:\Users\John Peter\Documents\visualfsharp\src\fsharp\FSharp.Build-proto\FSharp.Build-proto.fsproj" (Build target) (2)
 ->
(CallFsSrGen target) ->
  C:\Users\John Peter\Documents\visualfsharp\src\scripts\fssrgen.targets(27,5): error MSB3073: The command "C:\Users\Jo
hn Peter\Documents\visualfsharp\src\fsharp\FSharp.Build-proto\..\..\..\packages\FSharp.Compiler.Tools.4.0.1.19\tools\fs
i.exe --exec "C:\Users\John Peter\Documents\visualfsharp\src\scripts\fssrgen.fsx" "C:\Users\John Peter\Documents\visual
fsharp\src\fsharp\FSharp.Build\FSBuild.txt" "obj\Proto\net40\FSBuild.fs"  "obj\Proto\net40\FSBuild.resx" " exited with
code 9009. [C:\Users\John Peter\Documents\visualfsharp\src\fsharp\FSharp.Build-proto\FSharp.Build-proto.fsproj]


"C:\Users\John Peter\Documents\visualfsharp\src\fsharp-proto-build.proj" (default target) (1) ->
"C:\Users\John Peter\Documents\visualfsharp\src\fsharp\FSharp.Compiler-proto\FSharp.Compiler-proto.fsproj" (Build targe
t) (3) ->
  C:\Users\John Peter\Documents\visualfsharp\src\scripts\fssrgen.targets(27,5): error MSB3073: The command "C:\Users\Jo
hn Peter\Documents\visualfsharp\src\fsharp\FSharp.Compiler-proto\..\..\..\packages\FSharp.Compiler.Tools.4.0.1.19\tools
\fsi.exe --exec "C:\Users\John Peter\Documents\visualfsharp\src\scripts\fssrgen.fsx" "C:\Users\John Peter\Documents\vis
ualfsharp\src\fsharp\FSComp.txt" "obj\Proto\net40\FSComp.fs"  "obj\Proto\net40\FSComp.resx" " exited with code 9009. [C
:\Users\John Peter\Documents\visualfsharp\src\fsharp\FSharp.Compiler-proto\FSharp.Compiler-proto.fsproj]

**Comment by dsyme** [comment]
I believe this is fixed now, please verify.

**Comment by dsyme** [comment]
Fix was this direct commit: https://github.com/Microsoft/visualfsharp/commit/2d919b7312bd0541cbe37905739045128430b4df
