### ISSUE TITLE
No type coloring after installing VisualFSharpOpenSource.vsix

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#1878]
* Install VS 2017 RC
* Build VisualFSharp.sln in it.
* Install VisualFSharpOpenSource.vsix
* No type coloring (all other features works)

**Comment by dsyme** [comment]
fixed by https://github.com/Microsoft/visualfsharp/pulls/1877

**Comment by vasily-kirichenko** [comment]
It still does not work for me :(

VisualFSharpOpenSource.vsix, release:

![image](https://cloud.githubusercontent.com/assets/873919/20682036/43b2ed30-b5b7-11e6-92de-bb0e3d3d4388.png)

**Comment by vasily-kirichenko** [comment]
(Note that Ctrl+F5 works great (on vanilla RC))

**Comment by dsyme** [comment]
I get 

![capture8](https://cloud.githubusercontent.com/assets/7204669/20682131/9dbf2550-b59e-11e6-9cf3-ec997c1a7d1f.PNG)

**Comment by vasily-kirichenko** [comment]
:(

**Comment by vasily-kirichenko** [comment]
I've cleaned the sources and rebuilding from scratch. Hope it'll help.

**Comment by vasily-kirichenko** [comment]
OK, I removed 2017 Ent, installed 2017 Pro, built master from scratch, install open source release and I still don't have semantic coloring. What's more, it does not work on scripts:

![image](https://cloud.githubusercontent.com/assets/873919/20684405/d45ae82a-b5c0-11e6-88c3-3bdcf17a3ce7.png)

Any ideas how to clean things up?

**Comment by vasily-kirichenko** [comment]
OK, it finally works. I have to reinstall windows and VS and even that did not help until I changed "User Types" color setting to a different one, then revert to default. I think it's related to account settings synchronization.
