### ISSUE TITLE
Building VisualFSharpOpenSource fails on RC3

### ISSUE THREAD

**Issue by majocha** [Microsoft/visualfsharp#2356]
Building VisualFSharpOpenSource from current master with

`build vs`

fails on RC3

`"C:\visualfsharp\build-everything.proj" (default target) (1) ->
"C:\visualfsharp\vsintegration\fsharp-vsintegration-vsix-build.proj" (Build target) (34) ->
"C:\visualfsharp\vsintegration\Vsix\VisualFSharpOpenSource\VisualFSharpOpenSource.csproj" (Build target) (36) ->
(FindExistingDeploymentPath target) ->
  C:\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25929-RC2\tools\vssdk\Microsoft.VsSDK.targets(640,5): error VSSDK1043: There was a problem finding the extension with a VSIX identifier o
f "VisualFSharp". Value does not fall within the expected range. [C:\visualfsharp\vsintegration\Vsix\VisualFSharpOpenSource\VisualFSharpOpenSource.csproj]`

The same happens in Visual Studio with VisualFSharp.sln. it can't build VisualFSharpOpenSource.vsix project.

To follow up, I've tested this on several machines with RC3 installed. On some it works on some it doesn't. What the failing ones have in common is Visual Studio RC3 installed from scratch, not updated from RC2. I can't say if it's coincidence.

**Comment by vasily-kirichenko** [comment]
Delete `c:\Users\<you>\AppData\Local\Microsoft\VisualStudio\15.0_5280cf44FSharpDev\` folder (trailing numbers may vary).

**Comment by forki** [comment]
this is a common issue and should be addressed in VS

**Comment by majocha** [comment]
@vasily-kirichenko this usually worked for me but for some reason doesn't work this time.
I've even set up a fresh VM, installed RC3 from scratch. Still the same.
It worked fine on another machine with RC2, though.

To be clear the steps I just did:
1. [Fresh VM](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines)
2. Install VS2017 RC3, install F# RC3 release .msi and .vsix
3. checkout visualfsharp
4. `build debug` builds OK
5. 'build vs debug' fails

**Comment by vasily-kirichenko** [comment]
I conform `build vs debug` fails in the same way on my machine.

**Comment by vasily-kirichenko** [comment]
@KevinRansom @brettfo Maybe it's because RC3 bits has not yet merged to master?

**Comment by Pilchie** [comment]
I suspect/wonder if F# *also* needs a newer SDK NuGet reference. 

My understanding is that there was a breaking change to the SDK/Setup stuff late :-(

@brettfo can you sync up with @jaredpar about whether F# needs something like https://github.com/dotnet/roslyn/pull/16858?

**Comment by jaredpar** [comment]
Yeah that looks like one of the errors we were seeing.

**Comment by jaredpar** [comment]
Note this would require taking a new VS SDK NuGet and SWIX build.

**Comment by jaredpar** [comment]
Preparing a PR

**Comment by jaredpar** [comment]
PR sent for this change https://github.com/Microsoft/visualfsharp/pull/2357
