### ISSUE TITLE
StackOverflowException when compiling with FSharp.Compiler.Tools 4.1.1

### ISSUE THREAD

**Issue by alfonsogarciacaro** [Microsoft/visualfsharp#2682]
This seems to be a regression in the latest release of FSharp.Compiler.Tools (4.1.1).

After upgrading to latest FSharp.NET.Sdk (1.0.2 which has a dependency of FSharp.Compiler.Tools 4.1.1), when I build Fable and use it on a big project I get a StackOverflow exception. Unfortunately, because I cannot catch the exception I don't know exactly where it occurs but I have added logs to all my recursive functions and no one is repeating itself too much. The problem doesn't occur if I downgrade to FSharp.NET.Sdk 1.0.1 (which depends on FSharp.Compiler.Tools 4.1.10).

#### Repro steps

1. Clone Fable `narumi` branch using [this commit](https://github.com/fable-compiler/Fable/commit/e57a67dfc0bfce0a779a9deab679b849a33f886e) and build the project with the FAKE build script.

2. Start the Fable server by typing `dotnet build/fable/dotnet-fable.dll start` on the repo root.

3. In a new shell, go to the `src/dotnet/Fable.Client.Browser/demo` folder and type `npm run build`.

4. After some seconds a StackOverflow exception will crash the Fable server process. If you use [this commit](https://github.com/fable-compiler/Fable/commit/b6678d7fe166f0380ccd80b803a1e9e987ff1f3e) instead (which just downgrades FSharp.NET.Sdk) and repeat steps 1, 2 and 3, the crash won't happen.

#### Related information 

* Windows
* FSharp.Compiler.Tools 4.1.1
* dotnet SDK 1.0.1
* Indications of severity: Serious

**Comment by forki** [comment]
For the sake of making it very easy for contributors to reproduce: could
you please upload a zip with everything restored so that a single command
can reproduce the bug? Thanks

Am 22.03.2017 22:12 schrieb "Alfonso Garcia-Caro" <notifications@github.com

**Comment by alfonsogarciacaro** [comment]
My Fable folder is already 1.6GB ;) But I have prepared a trimmed version only with the things you should need (I've also added the FCS code that's necessary to build Fable's REPL), you can download it from [here](https://1drv.ms/u/s!Apwf9PG7zU1G1D24MnQDhoMLw5FM). After unzipping, please make sure you have dotnet SDK installed and then do steps 2 and 3 listed above.

**Comment by vasily-kirichenko** [comment]
Could you attach to the process with the debugger before it's alive? I believe it should show (very long) stack trace as SO raises.

**Comment by alfonsogarciacaro** [comment]
I've attached the debugger, and pausing it I get the following screenshot:

<img width="1280" alt="capture" src="https://cloud.githubusercontent.com/assets/8275461/24241332/c9e982ea-0fb4-11e7-8856-0609e12d4a44.PNG">

As you can see, there's some deep recursion happening to parse big AST expressions, but it's not in the number of hundreds of calls so I guess this shouldn't blow the stack.

However, letting the process run and pausing it later (a bit before it crashes I get):

<img width="1280" alt="capture2" src="https://cloud.githubusercontent.com/assets/8275461/24241456/32775684-0fb5-11e7-987f-a30f9af3355e.PNG">

In this case for a couple of workers "The maximum number of stack frames supported by Visual Studio has been exceeded", so I don't know how big the stack is for them. Is there another way to investigate it? I don't know either if the max number of stack frames supported by Visual Studio is close to what can cause a SO or not. But what puzzles me is this happens when building Fable with F# compiler 4.1.1 and not with 4.1.0. What could have happened in between that has caused this? Is there a tailcall optimization failing?

**Comment by vasily-kirichenko** [comment]
Use ProcDump https://technet.microsoft.com/en-us/sysinternals/dd996900.aspx Run it for watching your process, when the process crashes, it saves a dump. The dump can be opened in VS to debug.

**Comment by alfonsogarciacaro** [comment]
UPDATE: If I'm not messing up the builds. It seems the SO also occur when building Fable with F# compiler 4.1.0 with **Debug** config (but not in Release). With F# compiler 4.1.1 it happens both in Debug and Release configs (in previous F# compiler versions the problem didn't seem to happen at all).

I've created a [new zip](https://1drv.ms/u/s!Apwf9PG7zU1G1D7gcVt2kNuwHOa6) with FAKE build targets so you can try the different configs. As before, after each build run steps 2 and 3 mentioned above to see the crash happen.

```
BuildDebug_4.1.0
BuildRelease_4.1.0
BuildDebug_4.1.1
BuildRelease_4.1.1
```

> The only target that doesn't cause the SO is `BuildRelease_4.1.0`

**Comment by alfonsogarciacaro** [comment]
@vasily-kirichenko Thanks! Where's the dump file saved? I only see this:
<img width="422" alt="capture" src="https://cloud.githubusercontent.com/assets/8275461/24245526/85242c96-0fc3-11e7-91c9-e8e5830ce29e.PNG">
<img width="328" alt="capture2" src="https://cloud.githubusercontent.com/assets/8275461/24245529/88368f46-0fc3-11e7-8e85-fdef8317a57d.PNG">

**Comment by vasily-kirichenko** [comment]
I think somewhere in `Dump folder: ...` :)

**Comment by alfonsogarciacaro** [comment]
Hmm, I cannot find that `Dump` folder anywhere. Even giving the dump file a name (`procdump -ma -e dotnet.exe fable_fcs.dmp`) I cannot find it anywhere on my hard drive. Maybe the last message ("Dump count not reached") means the dump file hasn't been created?

**Comment by vasily-kirichenko** [comment]
Yeah, looks like it just output exceptions to the console. Play with cmd arguments. I forget the exact combination.

**Comment by enricosada** [comment]
add `-g` for managed 

with filter on first SO is (but try without filter maybe)

`procdump -ma -e 1 -f C00000FD.STACK_OVERFLOW -g -w <your process name>.exe`

**Comment by alfonsogarciacaro** [comment]
Thanks @enricosada. I found the same info in SO (the site). Unfortunately, when debugging the dump file with VS it tells me the source is not available, and I cannot read assembly :( 

<img width="1280" alt="capture" src="https://cloud.githubusercontent.com/assets/8275461/24247521/512e3cac-0fcc-11e7-95cb-2d87cb3430ec.PNG">

I've uploaded the [dump file here](https://1drv.ms/u/s!Apwf9PG7zU1G1D_-N7EWI6HWX7PD) in case you make better use of it.

**Comment by vasily-kirichenko** [comment]
Managed stuff was not dumped 

![image](https://cloud.githubusercontent.com/assets/873919/24248905/59be23f8-0fe2-11e7-91eb-a953579d6c7c.png)

**Comment by vasily-kirichenko** [comment]
There is a registry key where you can put a process name and a dump will be created every time it crashes. It produces better dumps. I completely forget where it is :(

**Comment by vasily-kirichenko** [comment]
Found it https://github.com/dotnet/roslyn/issues/16900#issuecomment-277034792
```
I think if you set:

HKLM\Software\Microsoft\Windows\Windows Error Reporting\LocalDumps\devenv.exe\DumpFolder to a folder on your machine,
HKLM\Software\Microsoft\Windows\Windows Error Reporting\LocalDumps\devenv.exe\DumpCount to the list of dumps to keep
HKLM\Software\Microsoft\Windows\Windows Error Reporting\LocalDumps\devenv.exe\DumpType to a Dword with the value 2 to keep full dumps.

You should see a full dump appear the next time this happens.
```

**Comment by alfonsogarciacaro** [comment]
Ok, now I'm really leaving my comfort zone ;) I don't know about these things so I have to Google and make guesses for any instruction that goes beyond copy&paste. I've tried the following:

```
reg add "HKLM\Software\Microsoft\Windows\Windows Error Reporting\LocalDumps\dotnet.exe\DumpFolder" /v C:\Dump

reg add "HKLM\Software\Microsoft\Windows\Windows Error Reporting\LocalDumps\dotnet.exe\DumpCount" /v 1

reg add "HKLM\Software\Microsoft\Windows\Windows Error Reporting\LocalDumps\dotnet.exe\DumpType" /v 2 /d REG_DWORD
```

No dump file was automatically created in C:\Dump. I tried again with procdump but the managed stuff didn't appear this time either.

I don't have more time available for this, so for now I'll just use the F# compiler 4.1.0 which seems to work. The package I prepared [above](https://github.com/Microsoft/visualfsharp/issues/2682#issuecomment-288686787) is still there if anyone with more experience in low-level debugging can give it a try.

**Comment by vasily-kirichenko** [comment]
The registry keys did work for me (for devenv.exe). And the dump was good.

**Comment by forki** [comment]
@vasily-kirichenko could you please try to reproduce?

**Comment by alfonsogarciacaro** [comment]
Seems fate has decided I cannot give up on this issue. In a happy? coincidence it just happened that I got another SO exception in my project at work so I used the procdump trick to get the dump file and that time it worked. So it occurred to me that I should try building Fable for full .NET Framework, I did it and still got the SO exception (which is a good thing because it means it's not a NETCore only thing) but happily the dump file showed the Managed code, so I could get the stack trace, please find it [here](https://gist.github.com/alfonsogarciacaro/d7eec5f7481f14f78964eca842631968). Apparently at some point F# print formatting is getting crazy.

**Comment by forki** [comment]
Wow

**Comment by vasily-kirichenko** [comment]
Looks like sformat enter endless loop on a specific recursive types group. Could you build an assembly containing that an instance of `EntityKind` so I can reference it and call `sprintf "%A"` on it to reproduce?

**Comment by alfonsogarciacaro** [comment]
Thank you @vasily-kirichenko! I'm attaching below a build of Fable.Core.dll (I built it for net45 hoping that'll be easier for you) with a static property `Fable.AST.Fable.EntityKind.Sample` that returns an EntityKind instance.

[Fable.Core.zip](https://github.com/Microsoft/visualfsharp/files/870093/Fable.Core.zip)

However, although it's true there seems to be a problem with the print formatting, I've also tried removing the `sprintf "%A"` calls (they were there mainly for debugging so they're not very important) but I'm still getting a SO exception (see capture below) when building with F# compiler 4.1.1 for net45 with Debug config (in Release mode I also get a SO in another place with similar stack trace). You can find the stack trace from the dump file [here](https://gist.github.com/alfonsogarciacaro/b41023b9a643406e00eb3513bf34812d). It's a deep call stack but it doesn't look too big to me. Maybe the latest F# compiler is somehow less tolerant to recursivity?

<img width="1275" alt="capture" src="https://cloud.githubusercontent.com/assets/8275461/24323080/9535c87a-1170-11e7-8b24-d4ca9e82974d.PNG">

**Comment by forki** [comment]
I can't repro. I added .paket folder to your sample and run `build.cmd BuildDebug_4.1.1`

![image](https://cloud.githubusercontent.com/assets/57396/24330690/9746e4d2-1224-11e7-8f5f-6049a7d1a55a.png)

**Comment by alfonsogarciacaro** [comment]
@forki The error is not in the build, you need to do steps 2. and 3. of the first post of this thread :)

**Comment by forki** [comment]
sigh

**Comment by forki** [comment]
I assume https://github.com/Microsoft/visualfsharp/blob/master/src/utils/sformat.fs#L1349 is recursive and calls the squashTo method and that calls the leadformatter again. @dsyme is that correct?

**Comment by dsyme** [comment]
@alfonsogarciacaro @forki I can take a look at this today/tomorrow.

I suspect either [this change](https://github.com/fsharp/FSharp.Compiler.Service/commit/ed948abaec8e2723c4fcafbde969a1071a4d72b1#diff-d394a7d9ed7a227da0c33ec249596510) or the addition of sprintf "%A" formatting for union types by default or both have conspired to cause this

What's the simplest repro steps?  Please remember I'm not normally doing Fable work

thanks

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for your help @forki, @dsyme!

@dsyme For your convenience I've created [the repro-so branch in Fable](https://github.com/fable-compiler/Fable/tree/repro-so) (I think that's easier than having to upload a .zip file somewhere every time) with a `ReproSO` FAKE target that runs all the necessary step automatically. So you just need to:

```
git clone https://github.com/fable-compiler/Fable
cd Fable
git checkout repro-so
.\build.cmd ReproSO
```

Info about the target:
- It builds Fable with dotnet SDK 1.0.1 + latest FSharp.Net.SDK (which has a dependency of F# compiler 4.1.1) targetting net45 (the bug also appears here and I guess it's easier to debug).
- Then runs `build\fable\dotnet-fable.exe` to compile FCS+Fable to JS (sorry, I haven't managed to create a smaller repro, this is the only time when I see the issue)
- In a few seconds the process should stop with the message `Process is terminated due to StackOverflowException.` This doesn't happen if I build Fable with F# compiler 4.1.0 in **Release** config.

As commented above, there seems to be a problem with the string formatting. However, I've added an additional target `ReproSONoPrintFormat` where I'm removing all the `sprintf` statements, but this is still raising an SO exception.

**Comment by dsyme** [comment]
@alfonsogarciacaro @forki I plan to look at this next.  I got distracted by some serious Linux packaging issues, but this is next on the list.

**Comment by alfonsogarciacaro** [comment]
@dsyme That'd be awesome, thank you! Although right now probably #2728 is more urgent as it's breaking many Fable projects (Fable 1.0 merges all files from referenced libraries in a single project so name collisions are more likely). This one at least can be fixed by using F# compiler 4.1.0.

**Comment by forki** [comment]
@alfonsogarciacaro yes but if the other one gets fixed and you upgrade then this one gets serious as well ;-)

**Comment by dsyme** [comment]
> Then runs build\fable\dotnet-fable.exe to compile FCS+Fable to JS 

I managed to repro the SO by doing

    .\build.cmd ReproSO

but this invbokes a lengthy set of operations and I need to be able to connect a debugger to the exact process that has the SO.

How do I see the exact command line that is being run that has the SO?  When I run

    build\fable\dotnet-fable.exe npm-run build

(after doing the ``    .\build.cmd ReproSO``) all I see is a window pop up and the SO doesn't happen again


In a few seconds the process should stop with the message Process is terminated due to StackOverflowException. This doesn't happen if I build Fable with F# compiler 4.1.0 in Release config.

**Comment by dsyme** [comment]
Ah, I see, I was in the wrong directory. This reproduces it:
```
C:\GitHub\fable\Fable\src\dotnet\Fable.Client.Browser\demo>..\..\..\..\build\fable\dotnet-fable.exe npm-run build
```

**Comment by dsyme** [comment]
Here's the stack for the true SO below.

This appears to be happening at the point where the fable compiler is trying to compile itself (which is all quite meta) - in particular it is compiling this very large function:
```
and private transformExpr (com: IFableCompiler) ctx fsExpr =
    match fsExpr with
```
This happens to also be the function that is executing. 

I suspect this is a "true" SO in that the expression being compiled is huge.  Either that part of the Fable compiler needs to be reimplemented to be tailcalling, or we need to reduce the size of that function by splitting it into pieces.  I'll try the latter.

```
 	Fable.Compiler.dll!Fable.FSharp2Fable.Patterns.|ForOf|_|(Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr _arg1)	Unknown
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	FSharp.Core.dll!Microsoft.FSharp.Primitives.Basics.List.mapToFreshConsTail<Fable.AST.Fable.Expr, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr>(Microsoft.FSharp.Collections.FSharpList<Fable.AST.Fable.Expr> cons, Microsoft.FSharp.Core.FSharpFunc<Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr, Fable.AST.Fable.Expr> f, Microsoft.FSharp.Collections.FSharpList<Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr> x)	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Primitives.Basics.List.map<Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr, Fable.AST.Fable.Expr>(Microsoft.FSharp.Core.FSharpFunc<Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr, Fable.AST.Fable.Expr> mapping, Microsoft.FSharp.Collections.FSharpList<Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr> x)	Unknown
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
>	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformExpr(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr fsExpr) Line 82	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.addMethod@945.Invoke(Fable.AST.SourceLocation range, Microsoft.FSharp.Core.FSharpOption<System.Tuple<string, string>> import, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpMemberOrFunctionOrValue meth, Microsoft.FSharp.Collections.FSharpList<Microsoft.FSharp.Collections.FSharpList<Microsoft.FSharp.Compiler.SourceCodeServices.FSharpMemberOrFunctionOrValue>> args, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr body) Line 1126	F#
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformDeclarations@1048-1.Invoke(Microsoft.FSharp.Compiler.SourceCodeServices.FSharpImplementationFileDeclaration decl) Line 1156	F#
 	FSharp.Core.dll!Microsoft.FSharp.Collections.ListModule.loop@219-29<System.__Canon, System.__Canon>(Microsoft.FSharp.Core.OptimizedClosures.FSharpFunc<System.__Canon, System.__Canon, System.__Canon> f, System.__Canon s, Microsoft.FSharp.Collections.FSharpList<System.__Canon> xs)	Unknown
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformDeclarations(Fable.FSharp2Fable.IFableCompiler com, Fable.FSharp2Fable.Context ctx, Microsoft.FSharp.Collections.FSharpList<Microsoft.FSharp.Compiler.SourceCodeServices.FSharpImplementationFileDeclaration> decls)	Unknown
 	Fable.Compiler.dll!Fable.FSharp2Fable.Compiler.transformFile(Fable.ICompiler com, Fable.ICompilerState state, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpCheckProjectResults checkedProject, string fileName) Line 143	F#
 	dotnet-fable.exe!Fable.Tools.State.compile(Fable.Tools.State.Compiler com, Fable.Tools.State.State state, string fileName) Line 205	F#
 	dotnet-fable.exe!Fable.Tools.State.loop@218-5.Invoke(Microsoft.FSharp.Core.Unit unitVar) Line 218	F#
 	FSharp.Core.dll!Microsoft.FSharp.Control.AsyncBuilderImpl.callA@841<Microsoft.FSharp.Core.Unit, Microsoft.FSharp.Core.Unit>.Invoke(Microsoft.FSharp.Control.AsyncParams<Microsoft.FSharp.Core.Unit> args)	Unknown
 	FSharp.Core.dll!<StartupCode$FSharp-Core>.$Control.loop@427-51(Microsoft.FSharp.Control.Trampoline this, Microsoft.FSharp.Core.FSharpFunc<Microsoft.FSharp.Core.Unit, Microsoft.FSharp.Control.FakeUnitValue> action)	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Control.Trampoline.ExecuteAction(Microsoft.FSharp.Core.FSharpFunc<Microsoft.FSharp.Core.Unit, Microsoft.FSharp.Control.FakeUnitValue> firstAction)	Unknown
 	FSharp.Core.dll!<StartupCode$FSharp-Core>.$Control.-ctor@511-1.Invoke(object state)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()	Unknown
 	mscorlib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch()	Unknown
```

**Comment by alfonsogarciacaro** [comment]
@dsyme Thanks for looking into this. It could possibly be this, but I'm surprised this only happens when building with the latest compiler version. The function is very big because it matches all the active patterns in the typed AST plus a few ones, but I guess I can try extracting all code that doesn't belong to the pattern match. I'll do it and come back to you :+1:

**Comment by dsyme** [comment]
@alfonsogarciacaro The compiler gets further if I split the method, but some later expression also causes an SO.  

I think some change in FCS or Fable must be chewing through more stack in some way.  So it fails with FCS 11.0.2 but succeeds with 11.0.1?

**Comment by alfonsogarciacaro** [comment]
@dsyme So there are two steps here:

1. Compile Fable to .NET: Use F# compiler 4.1.**1**
2. Use the compiled Fable (plus FCS.dll) to compile FCS+Fable source files to JS: the SO occurs

I haven't tried with different versions of FCS.dll, but I have noticed that when I do step 1 with F# compiler 4.1.**0** (with **Release** config) the SO doesn't happen in step 2. I can push another build target so you can see by yourself. Right now, [I'm making sure that F# compiler 4.1.0 is being called](https://github.com/fable-compiler/Fable/blob/narumi/src/dotnet/Fable.Tools/dotnet-fable.fsproj#L6-L7).

**Comment by dsyme** [comment]
> 1.	Compile Fable to .NET: Use F# compiler 4.1.1

Ah.  So you're saying that compiling with FSharp.Compiler.Tools 4.1.1 appears to produce an F# program that uses more stack than compiling with FSharp.Compiler.Tools 4.1.0.2?

**Comment by alfonsogarciacaro** [comment]
Yes, that seems to be the case.

**Comment by dsyme** [comment]
FWIW here's the diff: https://github.com/fsharp/fsharp/compare/4.1.0.2...4.1.1.  The main thing in that diff is this update:
```
-        "Microsoft.FSharp.Compiler.netcore": "1.0.0-rc-170122",
+        "Microsoft.FSharp.Compiler.netcore": "1.0.0-rc-170316-0"
```
That represents a significant chunk of work in the F# .NET Core compiler release, roughly speaking [all these changes](https://github.com/Microsoft/visualfsharp/compare/d9217259b0c2dd6bb8f9b3867f019fecbb1db2aa...d93e854842016ad15f09ef3cda47c516b63c12fd)

The problem could be something is disabling optimizations, or disabling tailcalls, or the wrong command line arguments are being passed, or ....

**Comment by dsyme** [comment]
@alfonsogarciacaro Hmmm.....

The ``repro-so`` branch I'm using has this in a few project files. But you also said that using FSharp.COmpiler.Tools 4.1.0 meant that the stack overflow disappeared? 
```
    <!-- See https://github.com/dotnet/netcorecli-fsc/issues/98 -->
    <FscToolPath>../../../lib/fsharp.compiler.tools.4.1.0</FscToolPath>
```

So I'm confused - if this makes the SO disappear then why am I seeing the SO?

**Comment by alfonsogarciacaro** [comment]
Yeah, sorry. That's because the `ReproSo` build target is actually [building the projects in `src/netfx`](https://github.com/fable-compiler/Fable/blob/870bb3d9ec97d02aa98e3aae9d5f6f68b81b1db3/build.fsx#L564-L565) which just use the F# compiler 4.1.1 (the default in FSharp.NET.Sdk 1.0.2) and target net45.

**Comment by dsyme** [comment]
@alfonsogarciacaro Ok, I see, thanks

**Comment by alfonsogarciacaro** [comment]
@dsyme I just pushed a `ReproNoSo` target that doesn't cause the SO: https://github.com/fable-compiler/Fable/commit/2afa0f18c41611a4b4d2b15c9db14b794b2206fc

1. Compile Fable as a netcoreapp1.0: Use F# compiler 4.1.0
2. Use the compiled Fable (plus FCS.dll) to compile FCS+Fable source files to JS: no SO occurs

**Comment by dsyme** [comment]
@alfonsogarciacaro So there are two differences there - 

The Fable compiler build by ``.\build.cmd ReproSO`` seems to be the debug one - is that right?  e.g. the "false" here in build.fsx

    buildTools "src/netfx" false ()

Gives:

![image](https://cloud.githubusercontent.com/assets/7204669/24555115/d699b608-1627-11e7-9b9e-926c5990dac5.png)

Does release also have this problem?

**Comment by dsyme** [comment]
Oh, I just see you changed that https://github.com/fable-compiler/Fable/commit/2afa0f18c41611a4b4d2b15c9db14b794b2206fc

I presume the SO still happens, am trying now

**Comment by alfonsogarciacaro** [comment]
Sorry, I just submitted a fix

**Comment by dsyme** [comment]
@alfonsogarciacaro I see you're switching between FSHarp.Compiler.Tools 4.1.0.2 and 4.1.1 - out of curiosity why are you also switching between .NET Fx and .NET Core? thx

**Comment by alfonsogarciacaro** [comment]
@dsyme I just did it because I imagined the .NET FX target would be easier to debug (for example, I didn't manage to get the stack with procdump when targeting netcore), but you can change the target and the SO will happen the same. The key seems to be the FSharp.Compiler.Tools 4.1.0.2 vs 4.1.1

**Comment by dsyme** [comment]
@alfonsogarciacaro OK.  This is quite hard :)

* Those compiler toolchains should really be generating essentially identical code and behaving identically. There are differences to be sure (see above) but I don't know of any differences in raw compiler logic that should be having such a dramatic effect.

* There are differences in the fsc command line build logic - @enricosada knows more about that - but again it's ultimately just a basic F# compilation.  I presume there are no differences in the actual flags passed through

All very odd....

**Comment by dsyme** [comment]
@alfonsogarciacaro  I'm still lost here.  I applied the diff below and ``build ReproSO`` still gives a stack overflow for me.  I thought switching to the 4.1.0 tools meant that the SO went away?  (In your ``build ReproNoSO`` you are also switching to .NET Core - this is staying with .NET Framework)

I'm trying your ``build ReproNoSo`` now to see if that removes the SO

![image](https://cloud.githubusercontent.com/assets/7204669/24557998/9461d2ca-1631-11e7-92dd-31cce43134f2.png)

Here's the SO:

![image](https://cloud.githubusercontent.com/assets/7204669/24558071/d363d1e4-1631-11e7-8b4f-789fc1883481.png)

**Comment by alfonsogarciacaro** [comment]
@dsyme I made a mistake with a the `ReproNoSo` target and commented some lines, not sure if you noticed. I sent a fix. Sorry for the mess, I'm not used to having so many fronts open.

You're right, that diff **should** prevent the SO exception in `ReproSO`, but I'm also getting it :/ The only difference with `ReproNoSo` should be the target and a compilation constant (NETFX) to make some APIs compatible.

But when targeting netcore, the SO doesn't appear when using FSharp.Compiler.Tools 4.1.0.2 and it does when using FCT 4.1.1 (you can try doing the opposite change (commenting the lines in the `src/dotnet` projects).

Again sorry for the mess, I'm also very perplexed.

**Comment by dsyme** [comment]
@alfonsogarciacaro 

OK, so I tried the diff below, which is src/dotnet/...  with the use of 4.1.0 commented out.  

But the ``build ReproNoSO`` succeeds - shouldn't we be expecting this to fail?  

![image](https://cloud.githubusercontent.com/assets/7204669/24559734/b6406518-1637-11e7-85dc-e7ed24ac32fd.png)

**Comment by dsyme** [comment]
@alfonsogarciacaro So basically I can't get the .NET Core version to SO yet.  And the .NET Framework version SO's all the time.  I'm wondering if it's an issue where the default stack size for .NET Framework is smaller?

**Comment by alfonsogarciacaro** [comment]
@dsyme I'm getting your same results :/

I'm completely puzzled because we did see the SO in netcore in the first place from [this commit](https://github.com/fable-compiler/Fable/commit/131819a834df1191add86a4382055e5c4aa8f8eb) on, which updated the `src/dotnet` projects to latest FSharp.NET.Sdk. FYI, @ncave made me notice it [here](https://github.com/fable-compiler/Fable/commit/5758b516f343acee133094db8e8f505bf6fcd31f#commitcomment-21406879).

Please don't spend more time on this atm. I'll try to isolate the problem better and come back to you. Sorry for the wrong leads.

**Comment by dsyme** [comment]
@alfonsogarciacaro For .NET Framework, using

    editbin /stack:10000000 ..\..\..\..\build\fable\dotnet-fable.exe

solves the problem - it pushes the default thread stack size up to near 10MB.  The windows default is 1MB IIRC.

You can set this on the F# compiler command line using ``/stackReserveSize:10000000`` though I haven't tried that

The deep stacks may potentially cause performance problems (repeated stack scanning by the GC) and it may ultimately be worth your while to root those out.  But for now I think that will solve your problem on .NET Framework.

**Comment by alfonsogarciacaro** [comment]
@dsyme Thanks, that's really helpful! Do you want me to close the issue or better to keep it open just in case?

**Comment by cloudRoutine** [comment]
@alfonsogarciacaro I can try to reimplement https://github.com/fable-compiler/Fable/blob/narumi/src/dotnet/Fable.Compiler/FSharp2Fable.fs#L149 so that it's tail recursive, do you want to go down that path?

**Comment by alfonsogarciacaro** [comment]
@cloudRoutine I would really appreciate the help, thank you! I opened https://github.com/fable-compiler/Fable/issues/787. Maybe we should continue the discussion there?
