### ISSUE TITLE
FS0193 internal error when running F# interactive

### ISSUE THREAD

**Issue by endeavour** [Microsoft/visualfsharp#2863]
I'm not sure of the cause but certain combinations of packages seem to cause F# interactive to crash with the error:
```
error FS0193: internal error: Value cannot be null.
Parameter name: con
```

#### Repro steps

I have created a small repository containing a set of dependencies that causes this issue:

https://github.com/endeavour/FS0193Repro

To reproduce:

1. Clone repository https://github.com/endeavour/FS0193Repro

2. Run bug.bat

#### Expected behavior

Prints "Hello World"

#### Actual behavior

FSI crashes with error
```
error FS0193: internal error: Value cannot be null.
Parameter name: con
```

#### Known workarounds

Unknown.

#### Related information 

Provide any related information 

Windows 10 version 1703
Microsoft (R) F# Interactive version 14.0.23020.0
.NET Runtime 4.6.1

**Comment by dsyme** [comment]
@endeavour Thanks for taking the time to make the repro.  However I haven't been able to get this fail using either fsi.exe from VS2015 or from VD201 or master

Any chance you could check if this repro's on master?
Thanks

**Comment by dsyme** [comment]
It could be that this was fixed here: https://github.com/Microsoft/visualfsharp/pull/707 but that fix was over a year ago now (though I think after the VS2015 release?)

**Comment by dsyme** [comment]
I'll close this for now since I believe it to have already been fixed.  But please reopen if I'm missing something or if you can repro on master

**Comment by endeavour** [comment]
I don't seem to have permission to re-open this ticket. I have just tried this on a machine with VS2017 RTM installed and still get the same issue.

**Comment by dsyme** [comment]
@endeavour Oh.  Can someone else please try to repro?  Thanks

**Comment by nbevans** [comment]
I repro'd it on my machine.

**Comment by dsyme** [comment]
@nbevans Thanks - could you list FSI.EXE  version info please?

**Comment by dsyme** [comment]
@nbevans @endeavour Here's some info from my machine, VS2017 cmd window
```
C:\GitHub\dsyme\visualfsharp\FS0193Repro>.paket\paket.bootstrapper.exe
Checking Paket version (downloading latest stable)...
Paket.exe 4.4.0 is up to date.

C:\GitHub\dsyme\visualfsharp\FS0193Repro>.paket\paket restore
Paket version 4.4.0
1 second - ready.

C:\GitHub\dsyme\visualfsharp\FS0193Repro>fsi fsibug\test.fsx
Hello world

C:\GitHub\dsyme\visualfsharp\FS0193Repro>where fsi
C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\fsi.exe

C:\GitHub\dsyme\visualfsharp\FS0193Repro>"C:\Program Files (x86)\Microsoft SDKs\
F#\4.1\Framework\v4.0\fsi.exe"

Microsoft (R) F# Interactive version 4.1
Copyright (c) Microsoft Corporation. All Rights Reserved.

C:\GitHub\dsyme\visualfsharp\FS0193Repro>dir "C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\fsi.exe"
 Volume in drive C is OSDisk
 Volume Serial Number is 8040-C97A

 Directory of C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0

24/02/2017  16:19           344,712 fsi.exe
               1 File(s)        344,712 bytes
               0 Dir(s)  23,626,735,616 bytes free

```
Here's another from a VS2015 cmd window:
```
C:\GitHub\dsyme\visualfsharp\FS0193Repro>bug

C:\GitHub\dsyme\visualfsharp\FS0193Repro>.paket\paket.bootstrapper.exe
Checking Paket version (downloading latest stable)...
Paket.exe 4.4.0 is up to date.

C:\GitHub\dsyme\visualfsharp\FS0193Repro>.paket\paket restore
Paket version 4.4.0
1 second - ready.

C:\GitHub\dsyme\visualfsharp\FS0193Repro>fsi fsibug\test.fsx
Hello world

C:\GitHub\dsyme\visualfsharp\FS0193Repro>where fsi
C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0\Fsi.exe

C:\GitHub\dsyme\visualfsharp\FS0193Repro>"C:\Program Files (x86)\Microsoft SDKs\
F#\4.0\Framework\v4.0\Fsi.exe"

Microsoft (R) F# Interactive version 14.0.23413.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

C:\GitHub\dsyme\visualfsharp\FS0193Repro>dir "C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0\Fsi.exe"
 Volume in drive C is OSDisk
 Volume Serial Number is 8040-C97A

 Directory of C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0

13/10/2015  12:49           319,112 Fsi.exe
               1 File(s)        319,112 bytes
               0 Dir(s)  23,626,670,080 bytes free

```

**Comment by dsyme** [comment]
Perhaps we have different libraries in the GAC.  Are there any GAC binding failures or odd exceptions raised when executing fsi.exe under a debugger?

**Comment by endeavour** [comment]
Tried running with VS debugger, no binding failures or exceptions:

```
stdin(1,1): error FS0078: Unable to find the file 'test.tsx' in any of
 C:\dev\FS0193Repro\FsiBug

> #load "test.fsx";;
[Loading C:\dev\FS0193Repro\FsiBug\Scripts\load-references-debug.fsx
 Loading C:\dev\FS0193Repro\FsiBug\Scripts\../AssemblyInfo.fs
 Loading C:\dev\FS0193Repro\FsiBug\Scripts\../Program.fs
 Loading C:\dev\FS0193Repro\FsiBug\Scripts\load-project-debug.fsx
 Loading C:\dev\FS0193Repro\FsiBug\test.fsx]
Binding session to 'C:\dev\FS0193Repro\FsiBug\Scripts\../../packages/FSharp.Cont
rol.AsyncSeq/lib/net45/FSharp.Control.AsyncSeq.dll'...
Binding session to 'C:\Program Files\Microsoft SDKs\Azure\.NET SDK\v2.9\bin\plug
ins\Diagnostics\Microsoft.WindowsAzure.Storage.dll'...

error FS0193: internal error: Value cannot be null.
Parameter name: con
```

**Comment by endeavour** [comment]
[fusion logs.zip](https://github.com/Microsoft/visualfsharp/files/941651/fusion.logs.zip)

I have attached the binding logs from fuslogvw.

**Comment by nbevans** [comment]
C:\Users\nbevans>fsi

Microsoft (R) F# Interactive version 14.0.23413.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

**Comment by dsyme** [comment]
OK, it's a case where we are binding to the wrong version of an assembly:
```
>  #load @"FsiBug\Test.fsx";;
[Loading C:\GitHub\dsyme\visualfsharp\FS0193Repro\FsiBug\Scripts\load-references
-debug.fsx
 Loading C:\GitHub\dsyme\visualfsharp\FS0193Repro\FsiBug\Scripts\../AssemblyInfo
.fs
 Loading C:\GitHub\dsyme\visualfsharp\FS0193Repro\FsiBug\Scripts\../Program.fs
 Loading C:\GitHub\dsyme\visualfsharp\FS0193Repro\FsiBug\Scripts\load-project-de
bug.fsx
 Loading C:\GitHub\dsyme\visualfsharp\FS0193Repro\FsiBug\Test.fsx]
Binding session to 'C:\GitHub\dsyme\visualfsharp\FS0193Repro\FsiBug\Scripts\../.
./packages/FSharp.Control.AsyncSeq/lib/net45/FSharp.Control.AsyncSeq.dll'...
Binding session to 'C:\GitHub\dsyme\visualfsharp\FS0193Repro\FsiBug\Scripts\../.
./packages/WindowsAzure.Storage/lib/net45/Microsoft.WindowsAzure.Storage.dll'...
```

For some reason your fsi.exe is not binding to ``./packages/WindowsAzure.Storage/lib/net45/Microsoft.WindowsAzure.Storage.dll'...``

**Comment by dsyme** [comment]
Can anyone repro on master?

Could you run this please?
```
fsi --resolutions fsibug\test.fsx
```

Since I can't repro this it's hard for me to debug it or validate a fix.

**Comment by endeavour** [comment]
```

james@ASGLH-WL-13361 C:\dev\FS0193Repro
$ fsi --resolutions fsibug\test.fsx


warning FS0075: The command-line option '' is for test purposes only

TargetFrameworkMoniker:

TargetFrameworkMonikerDisplayName:

TargetedRuntimeVersion:
    v4.0.30319
Assemblies:
    FSharp.Core, Version=4.4.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
AssemblyFiles:
CandidateAssemblyFiles:
TargetFrameworkDirectories:
    C:\Windows\Microsoft.NET\Framework\v4.0.30319\
InstalledAssemblyTables:
IgnoreInstalledAssemblyTable:
    False
SearchPaths:
    C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\
    C:\dev\FS0193Repro
    {TargetFrameworkDirectory}
    {Registry:Software\Microsoft\.NetFramework,v4.6.1,AssemblyFoldersEx}
    {AssemblyFolders}
    {GAC}
    C:\Windows\Microsoft.NET\Framework\v4.0.30319
AllowedAssemblyExtensions:
    .dll
    .exe
AllowedRelatedFileExtensions:
    .pdb
    .xml
    .pri
AppConfigFile:

AutoUnify:
    False
CopyLocalDependenciesWhenParentReferenceInGac:
    True
FindDependencies:
    False
TargetProcessorArchitecture:
    x86
StateFile:

InstalledAssemblySubsetTables:
IgnoreInstalledAssemblySubsetTable:
    False
TargetFrameworkSubsets:
FullTargetFrameworkSubsetNames:
ProfileName:

FullFrameworkFolders:
LatestTargetFrameworkDirectories:
ProfileTablesLocation:
Primary reference "FSharp.Core, Version=4.4.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
    Resolved file path is "C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\FSharp.Core.dll".
    Reference found at search path location "C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\".
    The ImageRuntimeVersion for this reference is "v4.0.30319".
TargetFrameworkMoniker:

TargetFrameworkMonikerDisplayName:

TargetedRuntimeVersion:
    v4.0.30319
Assemblies:
    FSharp.Core, Version=4.4.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
AssemblyFiles:
CandidateAssemblyFiles:
TargetFrameworkDirectories:
    C:\Windows\Microsoft.NET\Framework\v4.0.30319\
InstalledAssemblyTables:
IgnoreInstalledAssemblyTable:
    False
SearchPaths:
    C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\
    C:\dev\FS0193Repro
    {TargetFrameworkDirectory}
    {Registry:Software\Microsoft\.NetFramework,v4.6.1,AssemblyFoldersEx}
    {AssemblyFolders}
    {GAC}
    C:\Windows\Microsoft.NET\Framework\v4.0.30319
AllowedAssemblyExtensions:
    .dll
    .exe
AllowedRelatedFileExtensions:
    .pdb
    .xml
    .pri
AppConfigFile:

AutoUnify:
    False
CopyLocalDependenciesWhenParentReferenceInGac:
    True
FindDependencies:
    False
TargetProcessorArchitecture:
    x86
StateFile:

InstalledAssemblySubsetTables:
IgnoreInstalledAssemblySubsetTable:
    False
TargetFrameworkSubsets:
FullTargetFrameworkSubsetNames:
ProfileName:

FullFrameworkFolders:
LatestTargetFrameworkDirectories:
ProfileTablesLocation:
Primary reference "FSharp.Core, Version=4.4.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
    Resolved file path is "C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\FSharp.Core.dll".
    Reference found at search path location "C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\".
    The ImageRuntimeVersion for this reference is "v4.0.30319".
TargetFrameworkMoniker:

TargetFrameworkMonikerDisplayName:

TargetedRuntimeVersion:
    v4.0.30319
Assemblies:
    FSharp.Core, Version=4.4.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
AssemblyFiles:
CandidateAssemblyFiles:
TargetFrameworkDirectories:
    C:\Windows\Microsoft.NET\Framework\v4.0.30319\
InstalledAssemblyTables:
IgnoreInstalledAssemblyTable:
    False
SearchPaths:
    C:\dev\FS0193Repro\fsibug\Scripts
    C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\
    C:\dev\FS0193Repro\fsibug
    {TargetFrameworkDirectory}
    {Registry:Software\Microsoft\.NetFramework,v4.6.1,AssemblyFoldersEx}
    {AssemblyFolders}
    {GAC}
    C:\Windows\Microsoft.NET\Framework\v4.0.30319
AllowedAssemblyExtensions:
    .dll
    .exe
AllowedRelatedFileExtensions:
    .pdb
    .xml
    .pri
AppConfigFile:

AutoUnify:
    False
CopyLocalDependenciesWhenParentReferenceInGac:
    True
FindDependencies:
    False
TargetProcessorArchitecture:
    x86
StateFile:

InstalledAssemblySubsetTables:
IgnoreInstalledAssemblySubsetTable:
    False
TargetFrameworkSubsets:
FullTargetFrameworkSubsetNames:
ProfileName:

FullFrameworkFolders:
LatestTargetFrameworkDirectories:
ProfileTablesLocation:
Primary reference "FSharp.Core, Version=4.4.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
    Resolved file path is "C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\FSharp.Core.dll".
    Reference found at search path location "C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\".
        For SearchPath "C:\dev\FS0193Repro\fsibug\Scripts".
        Considered "C:\dev\FS0193Repro\fsibug\Scripts\FSharp.Core.dll", but it didn't exist.
        Considered "C:\dev\FS0193Repro\fsibug\Scripts\FSharp.Core.exe", but it didn't exist.
    The ImageRuntimeVersion for this reference is "v4.0.30319".
TargetFrameworkMoniker:

TargetFrameworkMonikerDisplayName:

TargetedRuntimeVersion:
    v4.0.30319
Assemblies:
    FSharp.Control.AsyncSeq.dll
AssemblyFiles:
CandidateAssemblyFiles:
TargetFrameworkDirectories:
    C:\Windows\Microsoft.NET\Framework\v4.0.30319\
InstalledAssemblyTables:
IgnoreInstalledAssemblyTable:
    False
SearchPaths:
    C:\dev\FS0193Repro\fsibug\Scripts
    C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\
    C:\dev\FS0193Repro\fsibug
    {TargetFrameworkDirectory}
    {Registry:Software\Microsoft\.NetFramework,v4.6.1,AssemblyFoldersEx}
    {AssemblyFolders}
    {GAC}
    C:\Windows\Microsoft.NET\Framework\v4.0.30319
AllowedAssemblyExtensions:
    .dll
    .exe
AllowedRelatedFileExtensions:
    .pdb
    .xml
    .pri
AppConfigFile:

AutoUnify:
    False
CopyLocalDependenciesWhenParentReferenceInGac:
    True
FindDependencies:
    False
TargetProcessorArchitecture:
    x86
StateFile:

InstalledAssemblySubsetTables:
IgnoreInstalledAssemblySubsetTable:
    False
TargetFrameworkSubsets:
FullTargetFrameworkSubsetNames:
ProfileName:

FullFrameworkFolders:
LatestTargetFrameworkDirectories:
ProfileTablesLocation:
Primary reference "FSharp.Control.AsyncSeq.dll".
        For SearchPath "C:\dev\FS0193Repro\fsibug\Scripts".
        Considered "C:\dev\FS0193Repro\fsibug\Scripts\FSharp.Control.AsyncSeq.dll.dll", but it didn't exist.
        Considered "C:\dev\FS0193Repro\fsibug\Scripts\FSharp.Control.AsyncSeq.dll.exe", but it didn't exist.
        Considered "C:\dev\FS0193Repro\fsibug\Scripts\FSharp.Control.AsyncSeq.dll", but it didn't exist.
        For SearchPath "C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\".
        Considered "C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\FSharp.Control.AsyncSeq.dll.dll", but it didn't exist.

        Considered "C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\FSharp.Control.AsyncSeq.dll.exe", but it didn't exist.

        Considered "C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\FSharp.Control.AsyncSeq.dll", but it didn't exist.
        For SearchPath "C:\dev\FS0193Repro\fsibug".
        Considered "C:\dev\FS0193Repro\fsibug\FSharp.Control.AsyncSeq.dll.dll", but it didn't exist.
        Considered "C:\dev\FS0193Repro\fsibug\FSharp.Control.AsyncSeq.dll.exe", but it didn't exist.
        Considered "C:\dev\FS0193Repro\fsibug\FSharp.Control.AsyncSeq.dll", but it didn't exist.
        For SearchPath "{TargetFrameworkDirectory}".
        Considered "C:\Windows\Microsoft.NET\Framework\v4.0.30319\FSharp.Control.AsyncSeq.dll.dll", but it didn't exist.
        Considered "C:\Windows\Microsoft.NET\Framework\v4.0.30319\FSharp.Control.AsyncSeq.dll.exe", but it didn't exist.
        Considered "C:\Windows\Microsoft.NET\Framework\v4.0.30319\FSharp.Control.AsyncSeq.dll", but it didn't exist.
        For SearchPath "{Registry:Software\Microsoft\.NetFramework,v4.6.1,AssemblyFoldersEx}".
        Considered AssemblyFoldersEx locations.
        For SearchPath "{AssemblyFolders}".
        Considered "C:\Program Files (x86)\Microsoft.NET\ADOMD.NET\130\FSharp.Control.AsyncSeq.dll.dll", but it didn't exist.
        Considered "C:\Program Files (x86)\Microsoft.NET\ADOMD.NET\130\FSharp.Control.AsyncSeq.dll.exe", but it didn't exist.
        Considered "C:\Program Files (x86)\Microsoft.NET\ADOMD.NET\130\FSharp.Control.AsyncSeq.dll", but it didn't exist.
        Considered "C:\Program Files (x86)\Microsoft SQL Server\130\SDK\Assemblies\FSharp.Control.AsyncSeq.dll.dll", but it didn't exist.
        Considered "C:\Program Files (x86)\Microsoft SQL Server\130\SDK\Assemblies\FSharp.Control.AsyncSeq.dll.exe", but it didn't exist.
        Considered "C:\Program Files (x86)\Microsoft SQL Server\130\SDK\Assemblies\FSharp.Control.AsyncSeq.dll", but it didn't exist.
        Considered "C:\Program Files\IIS\Microsoft Web Deploy V3\FSharp.Control.AsyncSeq.dll.dll", but it didn't exist.
        Considered "C:\Program Files\IIS\Microsoft Web Deploy V3\FSharp.Control.AsyncSeq.dll.exe", but it didn't exist.
        Considered "C:\Program Files\IIS\Microsoft Web Deploy V3\FSharp.Control.AsyncSeq.dll", but it didn't exist.
        Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.5\FSharp.Control.AsyncSeq.dll.dll", but it didn't exist.
        Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.5\FSharp.Control.AsyncSeq.dll.exe", but it didn't exist.
        Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.5\FSharp.Control.AsyncSeq.dll", but it didn't exist.
        Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.0\FSharp.Control.AsyncSeq.dll.dll", but it didn't exist.
        Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.0\FSharp.Control.AsyncSeq.dll.exe", but it didn't exist.
        Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.0\FSharp.Control.AsyncSeq.dll", but it didn't exist.
        For SearchPath "{GAC}".
        Considered "FSharp.Control.AsyncSeq.dll", which was not found in the GAC.
        For SearchPath "C:\Windows\Microsoft.NET\Framework\v4.0.30319".
        Considered "C:\Windows\Microsoft.NET\Framework\v4.0.30319\FSharp.Control.AsyncSeq.dll.dll", but it didn't exist.
        Considered "C:\Windows\Microsoft.NET\Framework\v4.0.30319\FSharp.Control.AsyncSeq.dll.exe", but it didn't exist.
        Considered "C:\Windows\Microsoft.NET\Framework\v4.0.30319\FSharp.Control.AsyncSeq.dll", but it didn't exist.
AssemblyFoldersEx location: "{Registry:Software\Microsoft\.NetFramework,v4.6.1,AssemblyFoldersEx}"
        C:\Program Files (x86)\Reference Assemblies\Microsoft\MSBuild\v14.0
        C:\Program Files (x86)\Microsoft.NET\Primary Interop Assemblies\
        C:\Program Files (x86)\Microsoft.NET\Primary Interop Assemblies\
        C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\ReferenceAssemblies\v4.5\
        C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\PublicAssemblies\
        C:\Program Files (x86)\Microsoft.NET\Primary Interop Assemblies\


        C:\Program Files\Microsoft SDKs\Azure\.NET SDK\v2.9\bin\plugins\Diagnostics\
        C:\Program Files\Microsoft SDKs\Azure\.NET SDK\v2.9\ref\Caching\
        C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\ReferenceAssemblies\v4.0\
        C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Tasks
        C:\Program Files (x86)\Microsoft SQL Server\130\DTS\PipelineComponents\
        C:\Program Files (x86)\Microsoft SQL Server\130\DTS\ForEachEnumerators
        C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Connections\
        C:\Program Files\Common Files\Microsoft Shared\Web Server Extensions\16\TEMPLATE\WorkflowActivities\
        C:\Program Files\Common Files\Microsoft Shared\Web Server Extensions\15\TEMPLATE\WorkflowActivities\
        C:\Program Files\Common Files\Microsoft Shared\Web Server Extensions\16\ISAPI\
        C:\Program Files\Common Files\Microsoft Shared\Web Server Extensions\15\ISAPI\
        C:\Program Files (x86)\Microsoft SDKs\RIA Services\v1.0\Libraries\Server\
        C:\Program Files (x86)\Open XML SDK\V2.5\lib
        C:\Program Files (x86)\Microsoft SDKs\Expression\Blend\.NETFramework\v4.0\Prototyping\Libraries\
        C:\Program Files (x86)\Microsoft SDKs\Expression\Blend\.NETFramework\v4.0\Libraries\
        C:\Program Files\Reference Assemblies\Microsoft\Microsoft Identity Extensions\1.0\
        C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\ReferenceAssemblies\v2.0\
        C:\Program Files\Microsoft SDKs\Azure\.NET SDK\v2.9\ref
        C:\Program Files (x86)\Common Files\Microsoft Shared\MSEnv\PublicAssemblies\
        C:\Program Files (x86)\Microsoft Chart Controls\Assemblies
        C:\Program Files\Microsoft SDKs\Azure\.NET SDK\v2.9\ref
TargetFrameworkMoniker:

TargetFrameworkMonikerDisplayName:

TargetedRuntimeVersion:
    v4.0.30319
Assemblies:
    FSharp.Control.AsyncSeq.exe
AssemblyFiles:
CandidateAssemblyFiles:
TargetFrameworkDirectories:
    C:\Windows\Microsoft.NET\Framework\v4.0.30319\
InstalledAssemblyTables:
IgnoreInstalledAssemblyTable:
    False
SearchPaths:
    C:\dev\FS0193Repro\fsibug\Scripts
    C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\
    C:\dev\FS0193Repro\fsibug
    {TargetFrameworkDirectory}
    {Registry:Software\Microsoft\.NetFramework,v4.6.1,AssemblyFoldersEx}
    {AssemblyFolders}
    {GAC}
    C:\Windows\Microsoft.NET\Framework\v4.0.30319
AllowedAssemblyExtensions:
    .dll
    .exe
AllowedRelatedFileExtensions:
    .pdb
    .xml
    .pri
AppConfigFile:

AutoUnify:
    False
CopyLocalDependenciesWhenParentReferenceInGac:
    True
FindDependencies:
    False
TargetProcessorArchitecture:
    x86
StateFile:

InstalledAssemblySubsetTables:
IgnoreInstalledAssemblySubsetTable:
    False
TargetFrameworkSubsets:
FullTargetFrameworkSubsetNames:
ProfileName:

FullFrameworkFolders:
LatestTargetFrameworkDirectories:
ProfileTablesLocation:
Primary reference "FSharp.Control.AsyncSeq.exe".
        For SearchPath "C:\dev\FS0193Repro\fsibug\Scripts".
        Considered "C:\dev\FS0193Repro\fsibug\Scripts\FSharp.Control.AsyncSeq.exe.dll", but it didn't exist.
        Considered "C:\dev\FS0193Repro\fsibug\Scripts\FSharp.Control.AsyncSeq.exe.exe", but it didn't exist.
        Considered "C:\dev\FS0193Repro\fsibug\Scripts\FSharp.Control.AsyncSeq.exe", but it didn't exist.
        For SearchPath "C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\".
        Considered "C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\FSharp.Control.AsyncSeq.exe.dll", but it didn't exist.

        Considered "C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\FSharp.Control.AsyncSeq.exe.exe", but it didn't exist.

        Considered "C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\FSharp.Control.AsyncSeq.exe", but it didn't exist.
        For SearchPath "C:\dev\FS0193Repro\fsibug".
        Considered "C:\dev\FS0193Repro\fsibug\FSharp.Control.AsyncSeq.exe.dll", but it didn't exist.
        Considered "C:\dev\FS0193Repro\fsibug\FSharp.Control.AsyncSeq.exe.exe", but it didn't exist.
        Considered "C:\dev\FS0193Repro\fsibug\FSharp.Control.AsyncSeq.exe", but it didn't exist.
        For SearchPath "{TargetFrameworkDirectory}".
        Considered "C:\Windows\Microsoft.NET\Framework\v4.0.30319\FSharp.Control.AsyncSeq.exe.dll", but it didn't exist.
        Considered "C:\Windows\Microsoft.NET\Framework\v4.0.30319\FSharp.Control.AsyncSeq.exe.exe", but it didn't exist.
        Considered "C:\Windows\Microsoft.NET\Framework\v4.0.30319\FSharp.Control.AsyncSeq.exe", but it didn't exist.
        For SearchPath "{Registry:Software\Microsoft\.NetFramework,v4.6.1,AssemblyFoldersEx}".
        Considered AssemblyFoldersEx locations.
        For SearchPath "{AssemblyFolders}".
        Considered "C:\Program Files (x86)\Microsoft.NET\ADOMD.NET\130\FSharp.Control.AsyncSeq.exe.dll", but it didn't exist.
        Considered "C:\Program Files (x86)\Microsoft.NET\ADOMD.NET\130\FSharp.Control.AsyncSeq.exe.exe", but it didn't exist.
        Considered "C:\Program Files (x86)\Microsoft.NET\ADOMD.NET\130\FSharp.Control.AsyncSeq.exe", but it didn't exist.
        Considered "C:\Program Files (x86)\Microsoft SQL Server\130\SDK\Assemblies\FSharp.Control.AsyncSeq.exe.dll", but it didn't exist.
        Considered "C:\Program Files (x86)\Microsoft SQL Server\130\SDK\Assemblies\FSharp.Control.AsyncSeq.exe.exe", but it didn't exist.
        Considered "C:\Program Files (x86)\Microsoft SQL Server\130\SDK\Assemblies\FSharp.Control.AsyncSeq.exe", but it didn't exist.
        Considered "C:\Program Files\IIS\Microsoft Web Deploy V3\FSharp.Control.AsyncSeq.exe.dll", but it didn't exist.
        Considered "C:\Program Files\IIS\Microsoft Web Deploy V3\FSharp.Control.AsyncSeq.exe.exe", but it didn't exist.
        Considered "C:\Program Files\IIS\Microsoft Web Deploy V3\FSharp.Control.AsyncSeq.exe", but it didn't exist.
        Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.5\FSharp.Control.AsyncSeq.exe.dll", but it didn't exist.
        Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.5\FSharp.Control.AsyncSeq.exe.exe", but it didn't exist.
        Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.5\FSharp.Control.AsyncSeq.exe", but it didn't exist.
        Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.0\FSharp.Control.AsyncSeq.exe.dll", but it didn't exist.
        Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.0\FSharp.Control.AsyncSeq.exe.exe", but it didn't exist.
        Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.0\FSharp.Control.AsyncSeq.exe", but it didn't exist.
        For SearchPath "{GAC}".
        Considered "FSharp.Control.AsyncSeq.exe", which was not found in the GAC.
        For SearchPath "C:\Windows\Microsoft.NET\Framework\v4.0.30319".
        Considered "C:\Windows\Microsoft.NET\Framework\v4.0.30319\FSharp.Control.AsyncSeq.exe.dll", but it didn't exist.
        Considered "C:\Windows\Microsoft.NET\Framework\v4.0.30319\FSharp.Control.AsyncSeq.exe.exe", but it didn't exist.
        Considered "C:\Windows\Microsoft.NET\Framework\v4.0.30319\FSharp.Control.AsyncSeq.exe", but it didn't exist.
AssemblyFoldersEx location: "{Registry:Software\Microsoft\.NetFramework,v4.6.1,AssemblyFoldersEx}"
        C:\Program Files (x86)\Reference Assemblies\Microsoft\MSBuild\v14.0
        C:\Program Files (x86)\Microsoft.NET\Primary Interop Assemblies\
        C:\Program Files (x86)\Microsoft.NET\Primary Interop Assemblies\
        C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\ReferenceAssemblies\v4.5\
        C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\PublicAssemblies\
        C:\Program Files (x86)\Microsoft.NET\Primary Interop Assemblies\


        C:\Program Files\Microsoft SDKs\Azure\.NET SDK\v2.9\bin\plugins\Diagnostics\
        C:\Program Files\Microsoft SDKs\Azure\.NET SDK\v2.9\ref\Caching\
        C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\ReferenceAssemblies\v4.0\
        C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Tasks
        C:\Program Files (x86)\Microsoft SQL Server\130\DTS\PipelineComponents\
        C:\Program Files (x86)\Microsoft SQL Server\130\DTS\ForEachEnumerators
        C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Connections\
        C:\Program Files\Common Files\Microsoft Shared\Web Server Extensions\16\TEMPLATE\WorkflowActivities\
        C:\Program Files\Common Files\Microsoft Shared\Web Server Extensions\15\TEMPLATE\WorkflowActivities\
        C:\Program Files\Common Files\Microsoft Shared\Web Server Extensions\16\ISAPI\
        C:\Program Files\Common Files\Microsoft Shared\Web Server Extensions\15\ISAPI\
        C:\Program Files (x86)\Microsoft SDKs\RIA Services\v1.0\Libraries\Server\
        C:\Program Files (x86)\Open XML SDK\V2.5\lib
        C:\Program Files (x86)\Microsoft SDKs\Expression\Blend\.NETFramework\v4.0\Prototyping\Libraries\
        C:\Program Files (x86)\Microsoft SDKs\Expression\Blend\.NETFramework\v4.0\Libraries\
        C:\Program Files\Reference Assemblies\Microsoft\Microsoft Identity Extensions\1.0\
        C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\ReferenceAssemblies\v2.0\
        C:\Program Files\Microsoft SDKs\Azure\.NET SDK\v2.9\ref
        C:\Program Files (x86)\Common Files\Microsoft Shared\MSEnv\PublicAssemblies\
        C:\Program Files (x86)\Microsoft Chart Controls\Assemblies
        C:\Program Files\Microsoft SDKs\Azure\.NET SDK\v2.9\ref
TargetFrameworkMoniker:

TargetFrameworkMonikerDisplayName:

TargetedRuntimeVersion:
    v4.0.30319
Assemblies:
    Microsoft.WindowsAzure.Storage.dll
AssemblyFiles:
CandidateAssemblyFiles:
TargetFrameworkDirectories:
    C:\Windows\Microsoft.NET\Framework\v4.0.30319\
InstalledAssemblyTables:
IgnoreInstalledAssemblyTable:
    False
SearchPaths:
    C:\dev\FS0193Repro\fsibug\Scripts
    C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\
    C:\dev\FS0193Repro\fsibug
    {TargetFrameworkDirectory}
    {Registry:Software\Microsoft\.NetFramework,v4.6.1,AssemblyFoldersEx}
    {AssemblyFolders}
    {GAC}
    C:\Windows\Microsoft.NET\Framework\v4.0.30319
AllowedAssemblyExtensions:
    .dll
    .exe
AllowedRelatedFileExtensions:
    .pdb
    .xml
    .pri
AppConfigFile:

AutoUnify:
    False
CopyLocalDependenciesWhenParentReferenceInGac:
    True
FindDependencies:
    False
TargetProcessorArchitecture:
    x86
StateFile:

InstalledAssemblySubsetTables:
IgnoreInstalledAssemblySubsetTable:
    False
TargetFrameworkSubsets:
FullTargetFrameworkSubsetNames:
ProfileName:

FullFrameworkFolders:
LatestTargetFrameworkDirectories:
ProfileTablesLocation:
Primary reference "Microsoft.WindowsAzure.Storage, Version=4.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35".
    Resolved file path is "C:\Program Files\Microsoft SDKs\Azure\.NET SDK\v2.9\bin\plugins\Diagnostics\Microsoft.WindowsAzure.Storage.dll".
    Reference found at search path location "{Registry:Software\Microsoft\.NetFramework,v4.6.1,AssemblyFoldersEx}".
        For SearchPath "C:\dev\FS0193Repro\fsibug\Scripts".
        Considered "C:\dev\FS0193Repro\fsibug\Scripts\Microsoft.WindowsAzure.Storage.dll.dll", but it didn't exist.
        Considered "C:\dev\FS0193Repro\fsibug\Scripts\Microsoft.WindowsAzure.Storage.dll.exe", but it didn't exist.
        Considered "C:\dev\FS0193Repro\fsibug\Scripts\Microsoft.WindowsAzure.Storage.dll", but it didn't exist.
        For SearchPath "C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\".
        Considered "C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\Microsoft.WindowsAzure.Storage.dll.dll", but it didn't exist.
        Considered "C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\Microsoft.WindowsAzure.Storage.dll.exe", but it didn't exist.
        Considered "C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\Microsoft.WindowsAzure.Storage.dll", but it didn't exist.
        For SearchPath "C:\dev\FS0193Repro\fsibug".
        Considered "C:\dev\FS0193Repro\fsibug\Microsoft.WindowsAzure.Storage.dll.dll", but it didn't exist.
        Considered "C:\dev\FS0193Repro\fsibug\Microsoft.WindowsAzure.Storage.dll.exe", but it didn't exist.
        Considered "C:\dev\FS0193Repro\fsibug\Microsoft.WindowsAzure.Storage.dll", but it didn't exist.
        For SearchPath "{TargetFrameworkDirectory}".
        Considered "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.WindowsAzure.Storage.dll.dll", but it didn't exist.
        Considered "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.WindowsAzure.Storage.dll.exe", but it didn't exist.
        Considered "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.WindowsAzure.Storage.dll", but it didn't exist.
        For SearchPath "{Registry:Software\Microsoft\.NetFramework,v4.6.1,AssemblyFoldersEx}".
        Considered AssemblyFoldersEx locations.
    The ImageRuntimeVersion for this reference is "v4.0.30319".
AssemblyFoldersEx location: "{Registry:Software\Microsoft\.NetFramework,v4.6.1,AssemblyFoldersEx}"
        C:\Program Files (x86)\Reference Assemblies\Microsoft\MSBuild\v14.0
        C:\Program Files (x86)\Microsoft.NET\Primary Interop Assemblies\
        C:\Program Files (x86)\Microsoft.NET\Primary Interop Assemblies\
        C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\ReferenceAssemblies\v4.5\
        C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\PublicAssemblies\
        C:\Program Files (x86)\Microsoft.NET\Primary Interop Assemblies\


        C:\Program Files\Microsoft SDKs\Azure\.NET SDK\v2.9\bin\plugins\Diagnostics\
        C:\Program Files\Microsoft SDKs\Azure\.NET SDK\v2.9\ref\Caching\
        C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\ReferenceAssemblies\v4.0\
        C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Tasks
        C:\Program Files (x86)\Microsoft SQL Server\130\DTS\PipelineComponents\
        C:\Program Files (x86)\Microsoft SQL Server\130\DTS\ForEachEnumerators
        C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Connections\
        C:\Program Files\Common Files\Microsoft Shared\Web Server Extensions\16\TEMPLATE\WorkflowActivities\
        C:\Program Files\Common Files\Microsoft Shared\Web Server Extensions\15\TEMPLATE\WorkflowActivities\
        C:\Program Files\Common Files\Microsoft Shared\Web Server Extensions\16\ISAPI\
        C:\Program Files\Common Files\Microsoft Shared\Web Server Extensions\15\ISAPI\
        C:\Program Files (x86)\Microsoft SDKs\RIA Services\v1.0\Libraries\Server\
        C:\Program Files (x86)\Open XML SDK\V2.5\lib
        C:\Program Files (x86)\Microsoft SDKs\Expression\Blend\.NETFramework\v4.0\Prototyping\Libraries\
        C:\Program Files (x86)\Microsoft SDKs\Expression\Blend\.NETFramework\v4.0\Libraries\
        C:\Program Files\Reference Assemblies\Microsoft\Microsoft Identity Extensions\1.0\
        C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\ReferenceAssemblies\v2.0\
        C:\Program Files\Microsoft SDKs\Azure\.NET SDK\v2.9\ref
        C:\Program Files (x86)\Common Files\Microsoft Shared\MSEnv\PublicAssemblies\
        C:\Program Files (x86)\Microsoft Chart Controls\Assemblies
        C:\Program Files\Microsoft SDKs\Azure\.NET SDK\v2.9\ref

error FS0193: internal error: Value cannot be null.
Parameter name: con


james@ASGLH-WL-13361 C:\dev\FS0193Repro
$
```

(With FSI from VS 2017 RTM, I haven't had a chance to try with latest build from master yet)

**Comment by dsyme** [comment]
Thanks.  OK can now repro this once I installed the "Azure .NET libraries" extension to Visual Studio, adding

    C:\Program Files\Microsoft SDKs\Azure\.NET SDK\v2.9

and the AssemblyFoldersEx key.  Will work on it

**Comment by endeavour** [comment]
Great, thanks :)

**Comment by dsyme** [comment]
Proposed fix is here: https://github.com/Microsoft/visualfsharp/pull/2887/

Thanks for chasing this bug down, I'd seen it before but never had a good repo
