### ISSUE TITLE
[.NET Core SDK projects] 15.3 preview 3: dependencies are not loaded in VS

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#3266]
The following solution builds fine in ionide and from command line but VS  15.3 preview 3 complains.

![image](https://user-images.githubusercontent.com/57396/27585202-860f8bf0-5b3b-11e7-80c6-9fb82e784c3f.png)

#### Repro steps

* clone https://github.com/fable-compiler/fable-suave-scaffold
* Open ClientServer.sln 
* Go to Client project Utils.fs

#### Expected behavior

Showing no errors

#### Actual behavior

VS reports missing Fable links

**Comment by isaacabraham** [comment]
Is this paket support being broken or something else?

**Comment by forki** [comment]
paket works fine from cmd line and in ionide

**Comment by forki** [comment]
btw: the Solution Explorer shows the deps correctly:

![image](https://user-images.githubusercontent.com/57396/27587401-944a38ec-5b44-11e7-9b6b-a9a05d989013.png)

**Comment by forki** [comment]
Ok this is only a problem with F#. I create one C# and one F# solution with dotnet new and run `paket convert-from-nuget` on it. I then added Newtosoft.Json as dependency to both projects:
 
[fsharp.zip](https://github.com/Microsoft/visualfsharp/files/1105425/fsharp.zip)
[csharp.zip](https://github.com/Microsoft/visualfsharp/files/1105427/csharp.zip)

In the C# project intellisense will show Newtonsoft namespace (takes a moment for background restore but then VS knows about it). In F# project it will not.

**Comment by forki** [comment]
Even if you just `dotnet new console -lang f#` and add the PackageReference without NuGet it does not work. [fsharp-nuget.zip](https://github.com/Microsoft/visualfsharp/files/1105444/fsharp-nuget.zip)

**Comment by Pilchie** [comment]
I think the general problem here is that the F# language service doesn't get the commandline arguments yet :-/, even though the project system and build do have them.

We're working on this for preview 4.  (@brettfo is hoping to look at it this week I think).

**Comment by forki** [comment]
Is this something that could be fixed here?

**Comment by Pilchie** [comment]
Even though I've had it explained to me 2 or 3 times now, I forget the exact details of what needs to happen here :-/

@srivatsn or @brettfo can you elaborate?

**Comment by forki** [comment]
I mean in the blog announcement we read F# support works so we were very
optimistic

Am 27.06.2017 6:30 nachm. schrieb "Kevin Pilch" <notifications@github.com>:

**Comment by enricosada** [comment]
yes, please @Pilchie ask to remove it from blog (cc @cartermp ) at least is not another disappoinment for F# ppl (and is annoying download a preview 5GB an nothings works)

**Comment by cartermp** [comment]
Which blog?  Neither the .NET nor VS blogs have announced a release saying that F# support works.  There are release notes which can be edited [here](https://www.visualstudio.com/en-us/news/releasenotes/vs2017-Preview-relnotes#dotnetcoreimprovements15P3), but that's the only thing I'm aware of.

**Comment by forki** [comment]
"F# Support: You can use the .NET CLI to create .NET Core console
applications and .NET Core /.NET Standard class libraries in F#. These
projects will load in this preview release of Visual Studio. We are still
working on templates to enable you to create these same projects from
within the IDE"

Am 27.06.2017 6:42 nachm. schrieb "Phillip Carter" <notifications@github.com

**Comment by enricosada** [comment]
anyway, language service and command line args bug aside, the new roslyn project system is really lightning fast (love i can edit any imported msbuild file, not just project, and it will instantly reload)

**Comment by cartermp** [comment]
I made the request to remove that bullet point completely from the release notes.

Just to clarify, the release notes are the only thing mentioning this.  There are no blog posts or announcements for F# support here, nor will there be any going on until the multiple things we have in-flight are all merged in their respective branches.

For now, there are ways to be unblocked if you use nightly releases of the .NET CLI.  Unfortunately, the entire process is horribly confusing right now because of different pieces across different products across different branches of those products being shipped into different previews.

**Comment by Pilchie** [comment]
>For now, there are ways to be unblocked if you use nightly releases of the .NET CLI. Unfortunately, the entire process is horribly confusing right now because of different pieces across different products across different branches of those products being shipped into different previews.

*BUT* We're going to work today on getting something documenting what you need to pull from where to get this working, right @cartermp ? 😉

**Comment by cartermp** [comment]
Yup.  I'll get instructions out as a part of an announcement on this repo w.r.t .NET Core support in VS.

**Comment by cartermp** [comment]
This is likely the same root cause as #3260, but surfacing as a different issue.

**Comment by bardeh** [comment]
Any idea on when this issue will be closed?
Anoying to get false errors in VS

**Comment by cartermp** [comment]
@bardeh This is for .NET Core SDK-based projects.  #3425 is what should address this, though it's not complete.

**Comment by cartermp** [comment]
This is now fixed in #3564.

![all-worky](https://user-images.githubusercontent.com/6309070/30306077-1d1e1306-972b-11e7-99a6-db793674e160.PNG)

**Comment by forki** [comment]
Is this already available in some form? Nightlies? Selfbuilt?

Am 12.09.2017 04:55 schrieb "Phillip Carter" <notifications@github.com>:

**Comment by davkean** [comment]
The CPS bits don't live in a public build yet.

**Comment by forki** [comment]
Yeah. That's what I feared.
Please let me know when I can test something. We have many many things to
try out...

Am 12.09.2017 09:09 schrieb "David Kean" <notifications@github.com>:

**Comment by davkean** [comment]
Apologies, I might be conflating things - thought I was replying to a question on a different issue, I'll let @cartermp confirm.

**Comment by vasily-kirichenko** [comment]
That's how Microsoft does OSS these days.

**Comment by davkean** [comment]
@vasily-kirichenko I was referring to the changes we made to core VS for F#. 

It would be akin to making a change to editor or other IDE pieces - this code isn't open source, so we need to wait for a public build with these pieces. It's a tradeoff; F# community can spend time rewriting these pieces as open source (and less time on F#) or you can consume non-open source features/extension points and spend more time on F#.

**Comment by davkean** [comment]
As a side note, it was only the critical piece that controls the order in which source files appear in the solution tree which we had to make in the closed source tree. The extensions that add managed support _are_ [all open source](http://github.com/dotnet/project-system).

**Comment by cartermp** [comment]
@forki No public build right now.  This required a fixed in closed-source parts of VS.

**Comment by kadmia** [comment]
Has this been fixed? I think I have the same issue. I just upgraded to 15.4.4 and still have the issue.

**Comment by cartermp** [comment]
This is fixed in the latest 15.5 Preview.
