### ISSUE TITLE
150+ warnings when building VisualFSharp from VS: NU1605: Detected package downgrade: [...]

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#3629]
As in the title, a large number of NU1605 Detected Package Downgrade are reported. 

Can this warning be ignored? Is it safe to switch off for the project? Or is it a sign that in my build I am referencing the wrong packages? (and if so, please advise).

## Repro steps

Just build `FSharp.sln` from within Visual Studio 2017.

## Expected behavior

No warnings.

## Actual behavior

Many warnings as mentioned in the title. Here's the full list:

```
Restoring NuGet packages...
To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
NU1605: Detected package downgrade: System.Collections.Immutable from 1.3.1 to 1.2.0. Reference the package directly from the project to select a different version. 
 FSharp.Compiler.Private (>= 1.0.0) -> System.Reflection.Metadata (>= 1.4.2) -> System.Collections.Immutable (>= 1.3.1) 
 FSharp.Compiler.Private (>= 1.0.0) -> System.Collections.Immutable (>= 1.2.0)
NU1605: Detected package downgrade: System.IO.FileSystem.Primitives from 4.3.0 to 4.0.1. Reference the package directly from the project to select a different version. 
 FSharp.Core.Unittests (>= 1.0.0) -> Microsoft.NETCore.App (>= 1.0.1) -> NETStandard.Library (>= 1.6.0) -> System.Console (>= 4.0.0) -> runtime.unix.System.Console (>= 4.3.0) -> System.IO.FileSystem.Primitives (>= 4.3.0) 
 FSharp.Core.Unittests (>= 1.0.0) -> Microsoft.NETCore.App (>= 1.0.1) -> NETStandard.Library (>= 1.6.0) -> System.IO.FileSystem.Primitives (>= 4.0.1)
NU1605: Detected package downgrade: System.Runtime.Handles from 4.3.0 to 4.0.1. Reference the package directly from the project to select a different version. 
 FSharp.Core.Unittests (>= 1.0.0) -> Microsoft.NETCore.App (>= 1.0.1) -> NETStandard.Library (>= 1.6.0) -> System.Console (>= 4.0.0) -> runtime.unix.System.Console (>= 4.3.0) -> System.Runtime.Handles (>= 4.3.0) 
 FSharp.Core.Unittests (>= 1.0.0) -> Microsoft.NETCore.App (>= 1.0.1) -> NETStandard.Library (>= 1.6.0) -> System.Runtime.Handles (>= 4.0.1)
NU1605: Detected package downgrade: System.Threading from 4.3.0 to 4.0.11. Reference the package directly from the project to select a different version. 
<snip />
... some 150 more of these warnings
```

## Known workarounds

None, but I would love to hear about them!

## Related information 

Visual Studio 2017 15.4.0 Preview 2, most recent master of `FSharp.sln`. Installed nightlies (though I doubt these matter, as these are NuGet warnings).

**Comment by dsyme** [comment]
Fixed by https://github.com/Microsoft/visualfsharp/pull/3641

**Comment by dsyme** [comment]
Fixed

**Comment by abelbraaksma** [comment]
@dsyme, I just rebuild everything and I still get the warnings. If I build FSharp.sln from within VS2017, does it even use the compiled `FSC.exe`? Because that could explain why I still have these errors.

**Comment by abelbraaksma** [comment]
@dsyme, just managed to test this, I have all tools, incl SDK tools up-to-date to master and still there's 166 of those warnings when compiling `FSharp.sln`. I think this needs to be reopened.

**Comment by cartermp** [comment]
Do you see this in `VisualFSharp.sln` as well?

**Comment by realvictorprm** [comment]
@abelbraaksma did you used a fresh clone / cleaned before?

(Visual F# is one if those repositories which are very critical about existing files and so often the solution is to clean, that's why I suggest. If it works it still should be investigated though)

**Comment by dsyme** [comment]
@realvictorprm This only happens when building inside Visual Studio, when restoring pacakges.  It doesn't happen when doing ``msbuild FSharp.sln /t:Restore`` for example. 

By default VS seems to do some extra kind of implicit restore that can involve encountering .NET Core 1.0 whackiness even when all your packages are for net45 only. It's very annoying. Perhaps it will go away when we move all project files to the new project file format

**Comment by cartermp** [comment]
I have no seen this in a long, long time. Closing, as infrastructure woes in this space have long been addressed.
