### ISSUE TITLE
No .NET Framework-based F# templates on 15.4.1.17102103 (Nightly)

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#3799]
![no-templates](https://user-images.githubusercontent.com/6309070/31898405-f2d94a5c-b7cd-11e7-95c1-97e45ebb9ef5.PNG)

Note that F# language support is installed, and I can open existing F# projects with no issue.

**Comment by cartermp** [comment]
Note: uninstalling the nightlies will make the templates show up again.

**Comment by cartermp** [comment]
Fixed by #3804.

**Comment by frederik-h** [comment]
I still have this problem with the current nightly build and VS 15.4.5.

**Comment by cartermp** [comment]
@frederik-h You must use VS15.5.x with the nightly releases. They are not compatible with older releases of Visual Studio.

**Comment by frederik-h** [comment]
This explains the problem. Unfortunately, at this time, I cannot update due to some C++ compiler changes in 15.5 ....  Thanks for the information.
